### ISSUE TITLE
Syntax error and more

### ISSUE THREAD

**Issue by Krossom** [samdenty99/injectify#15]
nodejs version:1.7.0

`
root@localhost:~/injectify# yarn run deploy
yarn run v1.7.0
$ run-script-os deploy

> injectify@1.0.0 deploy:linux:darwin /root/injectify
> yarn run deploy:start; (pm2 stop --silent injectify &> /dev/null; yarn run install:all && yarn run tsc && yarn run build && yarn run pm2) && yarn run deploy:success || yarn run deploy:failure

$ (cd ci && yarn && node status deploy-start)
[1/4] Resolving packages...
success Already up-to-date.
/root/injectify/server.config.js:41
    express: 3000,
           ^

**Comment by samdenty99** [comment]
> /root/injectify/server.config.js:41

You messed up the configuration file
