### ISSUE TITLE
simply function injectify.module('PageGhost', true) call in browser

### ISSUE THREAD

**Issue by jayesh6696** [samdenty99/injectify#16]
https://github.com/samdenty99/injectify/tree/24a414828e8428128c73fa70158f9ed436fe64a2/src/inject/core/modules/page-ghost

paperghost module from injectify.

i want that module extracted only 

so that when i place a certain js script src on any html page

and then i can initiate a websocket on any server with a specific port and i will get live view of the page, mouse clicks and dom objects
Please give me solution.

**Comment by samdenty99** [comment]
Injectify is a complete MiTM framework, it only works as a whole. If you want to extract modules, go ahead
