### ISSUE TITLE
Unable to install | Getting errors!

### ISSUE THREAD

**Issue by saikishorekate** [samdenty99/injectify#17]
![screenshot from 2018-09-25 00-00-24](https://user-images.githubusercontent.com/10182914/45971262-3ee95680-c056-11e8-8e3a-7b9fe0b3fec7.png)
![screenshot from 2018-09-25 00-00-31](https://user-images.githubusercontent.com/10182914/45971264-3f81ed00-c056-11e8-9ed6-f11fb8b4ab62.png)
![screenshot from 2018-09-25 00-00-34](https://user-images.githubusercontent.com/10182914/45971268-427cdd80-c056-11e8-896a-44e9bd8ec006.png)
![screenshot from 2018-09-25 00-00-38](https://user-images.githubusercontent.com/10182914/45971269-43157400-c056-11e8-80aa-f1edd4164771.png)
![screenshot from 2018-09-25 00-00-43](https://user-images.githubusercontent.com/10182914/45971270-43157400-c056-11e8-80c6-c1ff688e5f5c.png)
![screenshot from 2018-09-25 00-00-48](https://user-images.githubusercontent.com/10182914/45971271-4446a100-c056-11e8-8984-1735570faae2.png)

sudo npm i -g yarn
sudo yarn global add typescript
sudo yarn global add pm2
yarn run install:all
yarn run deploy 

**As described in documentation i have followed the steps first 4commands work fine, when i run yarn run deploy its not working to get the localhost:3000**

Thank You

**Comment by samdenty99** [comment]
Upgrade your node.js version

**Comment by samdenty99** [comment]
Upgrade your node.js version

**Comment by saikishorekate** [comment]
Done bro node v8.2.0
But Again Errors!

![screenshot from 2018-09-25 00-32-54](https://user-images.githubusercontent.com/10182914/45972931-b28d6280-c05a-11e8-9754-41341a1b36bd.png)
![screenshot from 2018-09-25 00-32-56](https://user-images.githubusercontent.com/10182914/45972933-b325f900-c05a-11e8-93b5-c3034b641dcb.png)
![screenshot from 2018-09-25 00-32-49](https://user-images.githubusercontent.com/10182914/45972945-b91bda00-c05a-11e8-974d-af50a96b5d79.png)

**Comment by samdenty99** [comment]
8.2 is old. Use 9 or 10

**Comment by samdenty99** [comment]
Rest syntax should work in 8.2 though, so you haven't updated it properly. `node -v`

**Comment by saikishorekate** [comment]
Yes, I am trying to update the node to 10 on Kali Linux but I am not finding the way to update!
NPM shows the stable version of  node

**Comment by saikishorekate** [comment]
[PM2][ERROR] Process injectify not found
 Its shows like red mark error!
Is this will be the problem?

**Comment by saikishorekate** [comment]
root@simss:~/injectify# yarn run deploy
yarn run v1.9.4
$ run-script-os deploy

> injectify@1.0.0 deploy:linux:darwin /root/injectify
> yarn run deploy:start; (pm2 stop --silent injectify &> /dev/null; yarn run install:all && yarn run tsc && yarn run build && yarn run pm2) && yarn run deploy:success || yarn run deploy:failure

$ (cd ci && yarn && node status deploy-start)
[1/4] Resolving packages...
success Already up-to-date.
$ yarn --production=false && cd ci && yarn  -production=false && cd ../interface/src && yarn --production=false && cd ../../src/inject/core && yarn --production=false && yarn run install:all
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
success Already up-to-date.
[PM2][ERROR] Process injectify not found
[1/4] Resolving packages...
success Already up-to-date.
$ yarn-recursive --cmd install
[1/4] Resolving packages...
success Already up-to-date.
Current yarn path: /root/injectify/src/inject/core/modules/debugger/package.json...
[1/4] Resolving packages...
success Already up-to-date.
Current yarn path: /root/injectify/src/inject/core/modules/page-ghost/src/package.json...
[1/4] Resolving packages...
success Already up-to-date.
Current yarn path: /root/injectify/src/inject/core/modules/tests/package.json...
[1/4] Resolving packages...
success Already up-to-date.
Current yarn path: /root/injectify/src/inject/core/package.json...
End of yarns
$ tsc || echo done. && yarn run modules && cd src/inject/core && yarn run build
src/main.ts(511,39): error TS2345: Argument of type '{}' is not assignable to parameter of type 'TemplateStringsArray'.
  Property 'raw' is missing in type '{}'.
src/main.ts(527,48): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(528,52): error TS2339: Property 'login' does not exist on type '{}'.
src/main.ts(571,7): error TS2322: Type '{}' is not assignable to type '{ previous: string; page: string; refresh: any; }'.
  Property 'previous' is missing in type '{}'.
src/main.ts(596,44): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(597,48): error TS2339: Property 'login' does not exist on type '{}'.
src/main.ts(672,31): error TS2339: Property 'title' does not exist on type '{}'.
src/main.ts(673,33): error TS2339: Property 'message' does not exist on type '{}'.
src/main.ts(674,28): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(717,17): error TS2339: Property 'project' does not exist on type '{ previous: string; page: string; refresh: any; }'.
src/main.ts(729,52): error TS2339: Property 'project' does not exist on type '{ previous: string; page: string; refresh: any; }'.
src/main.ts(735,33): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(753,33): error TS2339: Property 'data' does not exist on type '{}'.
src/main.ts(754,61): error TS2339: Property 'data' does not exist on type '{}'.
src/main.ts(755,47): error TS2339: Property 'data' does not exist on type '{}'.
src/main.ts(756,47): error TS2339: Property 'data' does not exist on type '{}'.
src/main.ts(1130,38): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(1136,40): error TS2339: Property 'title' does not exist on type '{}'.
src/main.ts(1137,42): error TS2339: Property 'message' does not exist on type '{}'.
src/main.ts(1141,58): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(1142,62): error TS2339: Property 'login' does not exist on type '{}'.
src/main.ts(1144,64): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(1146,53): error TS2339: Property 'login' does not exist on type '{}'.
src/main.ts(1149,65): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1179,54): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(1180,58): error TS2339: Property 'login' does not exist on type '{}'.
src/main.ts(1184,61): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1209,54): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1212,31): error TS2339: Property 'project' does not exist on type '{ previous: string; page: string; refresh: any; }'.
src/main.ts(1234,54): error TS2339: Property 'id' does not exist on type '{}'.
src/main.ts(1235,58): error TS2339: Property 'login' does not exist on type '{}'.
src/main.ts(1237,61): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1259,33): error TS2339: Property 'myPermissionLevel' does not exist on type '{}'.
src/main.ts(1290,43): error TS2339: Property 'title' does not exist on type '{}'.
src/main.ts(1291,45): error TS2339: Property 'message' does not exist on type '{}'.
src/main.ts(1338,47): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1353,55): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1392,58): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1407,46): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1414,37): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1457,48): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1459,60): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1462,54): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1463,54): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1465,54): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1479,50): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1480,50): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1482,50): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1501,50): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1502,50): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1504,63): error TS2339: Property 'doc' does not exist on type '{}'.
src/main.ts(1558,13): error TS2339: Property 'project' does not exist on type '{ previous: string; page: string; refresh: any; }'.
src/main.ts(1572,7): error TS2322: Type '{}' is not assignable to type '{ previous: string; page: string; refresh: any; }'.
  Property 'previous' is missing in type '{}'.
done.
$ cd src/inject/ && node TypingsGenerator.js
[inject:module-generator] Saved to ./core/definitions/modules.d.ts
$ cross-env NODE_ENV=production webpack --progress --colors --config ./webpack/production.config.js && cross-env NODE_ENV=production webpack --progress --colors --config ./webpack/debug.config.js
/root/injectify/src/inject/core/webpack/production.config.js:18
  ...shared({
  ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/root/injectify/src/inject/core/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/root/injectify/src/inject/core/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/root/injectify/src/inject/core/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/root/injectify/src/inject/core/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/root/injectify/src/inject/core/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /root/injectify/src/inject/core/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (native)
    at module.exports (/root/injectify/src/inject/core/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/root/injectify/src/inject/core/node_modules/webpack-cli/bin/webpack.js:239:39)
    at Object.parse (/root/injectify/src/inject/core/node_modules/yargs/yargs.js:543:18)
    at /root/injectify/src/inject/core/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/root/injectify/src/inject/core/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/injectify/src/inject/core/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ (cd ci && yarn && node status deploy-failure)
[1/4] Resolving packages...
success Already up-to-date.
Done in 135.83s.
