### ISSUE TITLE
Does not pass authentication

### ISSUE THREAD

**Issue by injectify-js** [samdenty99/injectify#21]
Hi. Does not pass authentication through the site https://injectify.samdd.me/ ?  Same problem on my server. What to do? Help please.

![inj](https://user-images.githubusercontent.com/38848541/47836400-37397200-ddb9-11e8-9a08-fa6759b2e84e.PNG)

**Comment by samdenty99** [comment]
I've shutdown the public instance of Injectify, you can host your own instance if you want to test it out / use it

**Comment by injectify-js** [comment]
On my server it does not pass the authorization using the service Authorization callback URL https://injectify.samdd.me
