### ISSUE TITLE
Web interface not coming up

### ISSUE THREAD

**Issue by gitxmax** [samdenty99/injectify#3]
Some logs:
https://i.imgur.com/spirRj4.png
https://i.imgur.com/oChQcOO.png
https://i.imgur.com/IojkgGe.png

**Comment by samdenty99** [comment]
Hey there, 

From the third screenshot, it seems it's having trouble connecting to the mongodb database, are you using mlab? If so make sure the mongodb URI is correct.

You still should be able to see the interface over at http://localhost:3000 without the database though => it'll just fail to log you in

**Comment by gitxmax** [comment]
Up and running, thanks for your help!

**Comment by emans841** [comment]
@gitmax am stuck here,how did you solve the issue
pm2 start injectify
[PM2] Applying action restartProcessId on app [injectify](ids: 0)
[PM2] [injectify](0) ✓
[PM2] Process successfully started
┌───────────┬──────┬────────┬─────┬─────┬───────────┐
│ Name      │ mode │ status │ ↺   │ cpu │ memory    │
├───────────┼──────┼────────┼─────┼─────┼───────────┤
│ injectify │ fork │ online │ 712 │ 50% │ 21.0 MB   │
└───────────┴──────┴────────┴─────┴─────┴───────────┘
 Use `pm2 show <id|name>` to get more details about an app
 yet i cant open it in my browser
