### ISSUE TITLE
[Question] LAN / WAN support

### ISSUE THREAD

**Issue by emans841** [samdenty99/injectify#5]
sorry does it work on LAN alone or can be use on WAN

**Comment by samdenty99** [comment]
Both. It can run on any Windows / Linux distro that supports NodeJS and has an active internet connection. I've had it successfully working on a Raspberry Pi Zero.

In the future I'm going to add a super-user control panel which will allow configuration of loads of stuff, with support for [localtunnel.me](https://localtunnel.me) allowing it to be accessed over the internet without a fixed ip address.
