### ISSUE TITLE
error when yarn run install:all 

### ISSUE THREAD

**Issue by emans841** [samdenty99/injectify#7]
root@kali:~# yarn run install:all
yarn run v1.5.1
error An unexpected error occurred: "Couldn't find a package.json file in \"/root\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by samdenty99** [comment]
Pretty self explanatory

> "Couldn't find a package.json file in "/root"

You need to switch the directory into the cloned Injectify one.
